# Generated by Django 3.2.6 on 2021-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveIntegerField(choices=[(0, 'Dépense'), (1, 'Revenu')], default=0),
        ),
    ]
